### ISSUE TITLE
reality count not getting updated on auto reality

### ISSUE THREAD

**Issue by galtgendo** [IvarK/AntimatterDimensionsSourceCode#3379]
I'm playing from https://ivark.github.io/AntimatterDimensions/ (in vivaldi).

I've just bought Nameless one softcap.

Auto reality is set to 1e41 and while it's reached in only a couple seconds, Reality Machines count doesn't go up...
[AD Save, Slot 1 #194 (2023-5-19).txt](https://github.com/IvarK/AntimatterDimensionsSourceCode/files/12148653/AD.Save.Slot.1.194.2023-5-19.txt)
(the date and save number is a bit bogus - I've been overwriting the file for quite awhile)

The count does properly go up with manual realities.

**Comment by cyip92** [comment]
A combination of the "instantly reality when no glyphs pass the filter" setting being on and your glyph filter settings being set to "Lowest Total Glyph Sacrifice" mode means that your auto-reality will always trigger immediately as soon as you unlock the reality study. This means that it doesn't have any extra time to build up many resources, and it will reality before many of your numbers get big.

In this case your RM is significantly lower than it would be than if you let it run a bit more before auto-realitying. You can see in your "Past Prestige Runs" subtab under statistics that these short realities are only actually giving you about e9 RM, which won't be contributing anything to your current total of e42. It might be a bit obtuse, but this is behaving exactly as intended.

**Comment by galtgendo** [comment]
...well, the explanation is sound, the way things work is silly....

Those settings are done while I want to farm RM and don't care about glyphs (cause they're significantly lower level than previously farmed). Having to remember to manually tick off "instant reality" besides just setting to auto-sacrifice is an extra click...

Technically, both are on the same tab, but as you've said, it's a bit obtuse...

Does it ever make sense for these two to apply simultaneously ?

**Comment by cyip92** [comment]
I don't think so - I take a look at making "Lowest sacrifice" mode disable the auto-reality filter setting, adjusting the auto-reality settings to be more comprehensive on the automation tab, and then adding a few more bits of information text as needed.
