### ISSUE TITLE
Googology Support

### ISSUE THREAD

**Issue by david19728** [IvarK/AntimatterDimensionsSourceCode#3387]
@IvarK 
**VERY URGENT!!!NO MORE PROCRASTINATION!!!!!**
@cyip92 DON'T CLOSE THIS😭😭😭😭😭😭😭😭😭😭

**Is your feature request related to a problem? Please describe.**
I want to make a mod and go past e9e15 antimatter.

**Describe the solution you'd like**
Migrate to [ExpantaNum.js](https://github.com/Naruyoko/ExpantaNum.js)

**Describe alternatives you've considered**
[OmegaNum.js](https://github.com/Naruyoko/OmegaNum.js)
[break_eternity.js](https://github.com/Patashu/break_eternity.js)
[logarithmica_numerus_lite.js](https://github.com/aarextiaokhiao/magna_numerus.js/blob/master/logarithmica_numerus_lite.js)

**Additional context**
WARNING:Notations (maybe except Scientific and Tetration) will becoming bad (at double exponential level) and break (at triple exponential level or tetrational level) ,so we need fix notation at Scientific on numbers which bigger than e9e15.

**Comment by IvarK** [comment]
Can you stop making duplicates of this? You got very good answers on the first issue you made about this, making more issues isn't going to change anything.
