### ISSUE TITLE
Selecting a glyph in a mobile browser

### ISSUE THREAD

**Issue by aar9nk** [IvarK/AntimatterDimensionsSourceCode#3401]
**Describe the bug**
Selecting a glyph on reality when in a mobile browser is very difficult. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Mobile browser
2. attempt reality
3. Click on glyph
4. Occasionally you'll get the tooltip, however it becomes very inconsistent to actually select a glyph
5. usually takes around 50 clicks

**Expected behavior**
I should be able to click on glyph and it be selected
**Screenshots**
![Capture](https://github.com/IvarK/AntimatterDimensionsSourceCode/assets/67638951/50e268d5-88da-4e24-9de9-eb8e76f17778)

**Savefile**
If applicable, add a pastebin link with a savefile.

**Additional context**
It appears removing this div fixes the problem. however I'm not too familiar with vue or the codebase so I can't really see why it is being used.

**Comment by earthernsence** [comment]
In the meantime, you can try playing on [this mod](https://asanned.github.io/AD_MWGP/), which I think has the issue fixed.
