### ISSUE TITLE
Can't click on login with google when playing on web browser on iphone

### ISSUE THREAD

**Issue by CCCBBBAAAHIGHSCORE** [IvarK/AntimatterDimensionsSourceCode#3409]
**Describe the bug**

I can't click on login with google when playing on web browser on iphone, when i try to, the game thinks i'm clicking on "import save from file", same thing if i click a random point below the login button
Some other people have the same bug, see here on reddit : https://old.reddit.com/r/AntimatterDimensions/comments/11e5k16/cannot_login_with_google_from_mobile_web/

**To Reproduce**

play on safari on iphone, 
try to click on login with google,
witness that it click on import save from file, instead.
be sad

**Expected behavior**
i want to login with gooooogle

Thanks

**Comment by Phoenix51505** [comment]
Playing web reality on Mobile devices is not particularly supported, unfortunately.
