### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by mimikun** [IvarK/AntimatterDimensionsSourceCode#3415]
**Is your feature request related to a problem? Please describe.**
This game can only be played in English. Therefore, I have no choice but to use Google Translate in one hand. Also, even if I wanted to recommend this game to my friends, I can't (my friends can't read English 😢 ).

**Describe the solution you'd like**
Add locale files to enable localization

**Describe alternatives you've considered**
Use Google Translate or DeepL

**Additional context**
If you would like to consider this, I would be happy to contribute. I'm a native Japanese

**Comment by Dystopia-user181** [comment]
The way the game UI is structured currently makes it hard to do localisation, and I'm afraid there aren't really any developers who are committed enough to the game currently to significantly rewrite it.

Meanwhile, you can play on the android version which does have proper language changing support (Or an android emulator if you are on a PC)

**Comment by mimikun** [comment]
Thanks! I'm close this issue.
