### ISSUE TITLE
New reality didn't work

### ISSUE THREAD

**Issue by Littlesoro** [IvarK/AntimatterDimensionsSourceCode#3416]
**Describe the bug**
When the reality is available to start I can't do it

**To Reproduce**
Playing in Chrome in Android device
After the reality is enable to restart nothing happen when I click in glyph to chose which one I'll pick-up.

**Expected behavior**
Restart the reality with the glyph chosen

**Comment by Dystopia-user181** [comment]
The site is not intended to be used on mobile, we have the android version on the app store for that
