### ISSUE TITLE
Weird behavior when tapping on the "unlock Xth time dimension" buttons to check time remaining

### ISSUE THREAD

**Issue by GroggyOtter** [IvarK/AntimatterDimensionsSourceCode#3457]
Not sure if this is a UI improvement or bug.
Tapping the "Unlock the 5th/6th/7th/8th Time Dimension" before you can buy them to check the time causes the UI to shoot upward, forcing everything off the screen and displaying the time up at the top of the screen.

Tapping on the "Unlock 7th time dimension" option here:  
![Screenshot_20240803_213154_Antimatter Dimensions2](https://github.com/user-attachments/assets/a3496782-5d4a-4ba7-8a40-d9cfacacfab8)

Makes this happen:  
![Screenshot_20240803_213040_Antimatter Dimensions2](https://github.com/user-attachments/assets/c575d218-8933-4b34-bb74-04827ed61cc9)

**Comment by GroggyOtter** [comment]
IvarK...you gonna address this?  
30 days since the report with no response = stale post.

**Comment by IvarK** [comment]
The web version is not mobile optimized, and won't be as we have the mobile version.

**Comment by GroggyOtter** [comment]
The web version has nothing to do with this.
This is pertaining to the Android app. The one you download from the Play Store.
I didn't even know there was a web version of this game...

**Comment by kajfik** [comment]
idk how to fix this
