### ISSUE TITLE
Glyph filters do not work properly during certain stages of the game

### ISSUE THREAD

**Issue by CursedSliver** [IvarK/AntimatterDimensionsSourceCode#3466]
**Describe the bug**
The "Specified effect" (and possibly "Effect score") glyph filters do not work properly with the auto-reality checkbox (recycle icon to auto-reality if no glyphs will be kept). Namely, it sometimes fails to perform a reality when it can, and only when the rarity requirement and effect count is met but not necessarily the other requirements. The incorrect glyphs will still not be kept.

**To Reproduce**
1. Be on Safari or Brave 
2. Load this save: [https://pastebin.com/ZnjFvrY6](https://pastebin.com/ZnjFvrY6)
3. Skip offline progress and then manually reality.
4. Wait (switching to another tab for a bit might help). Do not adjust any settings. At some point the auto realitying should stop with the specified glyphs being not present. (manually realitying at this point will not keep any glyphs)

**Expected behavior**
Only stops auto-realitying if the correct glyphs can be obtained this reality. However, so far, it has not yet managed to obtain any correct glyphs while having a rarity threshold of 90.

**Screenshots**
![Screenshot_2024-10-13_at_21 14 57](https://github.com/user-attachments/assets/6ca6ef6a-19dc-4162-8179-30c18d0a78f4)

**Context**
After a certain point in progression, the issue appears to stop existing. I suspect that the issue stops existing after 4-effect glyphs can be obtained, but it may be some other factors that I do not know of.

**Comment by HexaVault** [comment]
"require conversion rate"
"glyph does not have conversion rate"

no bug here

**Comment by CursedSliver** [comment]
It says that it "must include all of the following effects", but conversion rate is not included
